#image: "python:3.7"

#build-docker-images:
#  script:
#  - docker build gemini/fitsarchiveutils:gitlab-ci -f Dockerfile-centos8-jenkins .
#  - docker build gemini/archive:gitlab-ci -f Dockerfile-archive-centos8-jenkins .
#  - docker container rm fitsdata-jenkins || true
#  - docker container rm archive-jenkins || true

before_script:
  - python --version
  - pip install -r requirements.txt

test:
  tags: ["shell"]
  script: "pytest --ignore tests/web/test_web_response.py tests"
