#image: "python:3.7"

stages:
  - lint
  - test
  - deploy

#build-docker-images:
#  script:
#  - docker build gemini/fitsarchiveutils:gitlab-ci -f Dockerfile-centos8-jenkins .
#  - docker build gemini/archive:gitlab-ci -f Dockerfile-archive-centos8-jenkins .
#  - docker container rm fitsdata-jenkins || true
#  - docker container rm archive-jenkins || true

#before_script:
#  - python --version
#  - pip install -r requirements.txt


flake8:
  stage: lint
  tags: ["shell"]
  script:
    - flake8 --max-line-length=120
  allow_failure: true

pylint:
  stage: lint
  allow_failure: true
  script:
    - pylint
  allow_failure: true

test:
  tags: ["shell"]
  script: "echo TBD"
  #script: "pytest --ignore tests/web/test_web_response.py tests"

# This won't work until we sort out some sort of password/permission process
run script:
  stage: deploy
  tags: ["shell", "python"]
  dependencies:
    - test
    - flake8
    - pylint
  script:
    - pip3 install ansible
    - ansible --version
    - cd ansible
    - ansible-playbook -i dev playbooks/archive_install.yml
  allow_failure: true
  when: manual
