import pytest
from fits_storage.web.selection import getselection

getselection_pairs = [
    (['12345'], {'notrecognised': '12345'}),
    (['123 456'], {'notrecognised': '123 456'}),
    (['gemini-north'], {'telescope': 'Gemini-North'}),
    (['GEMINI-SOUTH'], {'telescope': 'Gemini-South'}),
    (['19700101'], {'date': '19700101'}),
    (['20991231'], {'date': '20991231'}),
    (['21000101'], {'notrecognised': '21000101'}),
    (['20140101-20150101'], {'daterange': '20140101-20150101'}),
    (['GN-CAL20150623'], {'program_id': 'GN-CAL20150623'}),
    (['GN-CAL20150623-21', 'GN-CAL20150623'], {'program_id': 'GN-CAL20150623'}),
    (['GN-CAL20150623-21-001', 'GN-CAL20150623'], {'program_id': 'GN-CAL20150623'}),
    (['progid=GN-CAL20150623'], {'program_id': 'GN-CAL20150623'}),
    (['GN-CAL20150623-21'], {'observation_id': 'GN-CAL20150623-21'}),
    (['obsid=GN-CAL20150623'], {'observation_id': 'GN-CAL20150623'}), # Maybe this shouldn't be allowed?
    (['GN-CAL20150623-21-001'], {'data_label': 'GN-CAL20150623-21-001'}),
    # Instrument...
    (['gMoS'],  {'inst': 'GMOS'}),
    (['gMoS-n'],  {'inst': 'GMOS-N'}),
    (['gMoS-S'],  {'inst': 'GMOS-S'}),
    (['NiRi'],  {'inst': 'NIRI'}),
    (['niFS'],  {'inst': 'NIFS'}),
    (['NicI'],  {'inst': 'NICI'}),
    (['GNirs'], {'inst': 'GNIRS'}),
    (['MichELLE'],  {'inst': 'michelle'}),
    (['phOEnix'],  {'inst': 'PHOENIX'}),
    (['teXES'],  {'inst': 'TEXES'}),
    (['Trecs'],  {'inst': 'TReCS'}),
    (['HOKUPA+quirc'],  {'inst': 'Hokupaa+QUIRC'}),
    (['HOKUPAA+++quirc'],  {'inst': 'Hokupaa+QUIRC'}),
    (['GSaoi'],  {'inst': 'GSAOI'}),
    (['osCIR'],  {'inst': 'OSCIR'}),
    (['f2'],  {'inst': 'F2'}),
    (['gPi'],  {'inst': 'GPI'}),
    (['abu'],  {'inst': 'ABU'}),
    (['bhroS'],  {'inst': 'bHROS'}),
    (['HrWfS'],  {'inst': 'hrwfs'}),
    (['fLAMINGOs'],  {'inst': 'FLAMINGOS'}),
    (['cirpass'],  {'inst': 'CIRPASS'}),
    # Test what happens when you pass more than one instrument
    (['niri', 'nici', 'trecs', 'gmos', 'nici'], {'inst': 'NICI'}),
    (['N20310101S000'], {'notrecognised': 'N20310101S000'}),
    (['N20010101S000'], {'filepre': 'N20010101S000'}),
    (['filepre=N20310101S000'], {'filepre': 'N20310101S000'}),
    (['N20990101S0001'], {'filename': 'N20990101S0001.fits'}),
    (['N20010101S0001.fits'], {'filename': 'N20010101S0001.fits'}),
    (['N20990101S0001.fits'], {'filename': 'N20990101S0001.fits'}),
    (['N21000101S0001.fits'], {'notrecognised': 'N21000101S0001.fits'}),
    (['filename=foobarbaz'], {'filename': 'foobarbaz'}),
    (['DARK'], {'observation_type': 'DARK'}),
    (['OBJECT'], {'observation_type': 'OBJECT'}),
    (['PINHOLE'], {'observation_type': 'PINHOLE'}),
    (['RONCHI'], {'observation_type': 'RONCHI'}),
    (['ronchi'], {'notrecognised': 'ronchi'}),
    (['dayCal'], {'observation_class': 'dayCal'}),
    (['science'], {'observation_class': 'science'}),
    (['dark'], {'caltype': 'dark'}),
    (['specphot'], {'caltype': 'specphot'}),
    (['PROCESSED_FLAT'], {'reduction': 'PROCESSED_FLAT'}),
    (['R600'], {'disperser': 'R600'}),
    (['disperser=R600'], {'disperser': 'R600'}),
    (['camera=foobar'], {'camera': 'foobar'}),
    (['NS0.75arcsec'], {'focal_plane_mask': 'NS0.75arcsec'}),
    (['GN2014A#314-32'], {'focal_plane_mask': 'GN2014A#314-32'}),
    (['mask=foobar'], {'focal_plane_mask': 'foobar'}),
    (['warnings'], {'caloption': 'warnings'}),
    (['missing'], {'caloption': 'missing'}),
    (['requires'], {'caloption': 'requires'}),
    (['takenow'], {'caloption': 'takenow'}),
    (['imaging'], {'spectroscopy': False}),
    (['spectroscopy'], {'spectroscopy': True}),
    (['IFS'], {'mode': 'IFS', 'spectroscopy': True}),
    (['imaging', 'MOS'], {'mode': 'MOS', 'spectroscopy': True}),
    (['Win'], {'qa_state': 'Win'}),
    (['AnyQA'], {'qa_state': 'AnyQA'}),
    (['LGS'], {'lgs': 'LGS', 'ao': 'AO'}),
    (['NGS'], {'lgs': 'NGS', 'ao': 'AO'}),
    (['AO'], {'ao': 'AO'}),
    (['NOTAO'], {'ao': 'NOTAO'}),
    (['present'], {'present': True}),
    (['Present'], {'present': True}),
    (['notpresent'], {'present': False}),
    (['NotPresent'], {'present': False}),
    (['canonical'], {'canonical': True}),
    (['Canonical'], {'canonical': True}),
    (['notcanonical'], {'canonical': False}),
    (['NotCanonical'], {'canonical': False}),
    (['engineering'], {'engineering': True}),
    (['notengineering'], {'engineering': False}),
    (['includeengineering'], {'engineering': 'Include'}),
    (['science_verification'], {'science_verification': True}),
    (['notscience_verification'], {'science_verification': False}),
    (['filter=blah'], {'filter': 'blah'}),
    (['Filter=blah'], {'filter': 'blah'}),
    (['object=bleh'], {'object': 'bleh'}),
    (['Object=bleh'], {'object': 'bleh'}),
    (['1x2'], {'binning': '1x2'}),
    (['4x1'], {'binning': '4x1'}),
    (['6x1'], {'notrecognised': '6x1'}),
    (['photstandard'], {'photstandard': True}),
    (['low'], {'detector_config': ['low']}),
    (['low', 'NodAndShuffle'], {'detector_config': ['low', 'NodAndShuffle']}),
    (['Bright', 'low', 'NodAndShuffle'], {'detector_config': ['Bright', 'low', 'NodAndShuffle']}),
    (['centralspectrum'], {'detector_roi': 'Central Spectrum'}),
    (['central256'], {'detector_roi': 'Central256'}),
    (['twilight'], {'twilight': True}),
    (['nottwilight'], {'twilight': False}),
    (['Az=kkk'], {'az': 'kkk'}),
    (['Azimuth=kkk'], {'az': 'kkk'}),
    (['El=kkk'], {'el': 'kkk'}),
    (['elevation=kkk'], {'el': 'kkk'}),
    (['RA=fjfj'], {'ra': 'fjfj'}),
    (['DEC=fjfj'], {'notrecognised': 'DEC=fjfj'}),
    (['Dec=fjfj'], {'dec': 'fjfj'}),
    (['SR=kjkj'], {'sr': 'kjkj'}),
    (['crpa=kjkj'], {'crpa': 'kjkj'}),
    (['Crpa=kjkj'], {'notrecognised': 'Crpa=kjkj'}),
    (['cenwlen=blahblah'], {'cenwlen': 'blahblah'}),
    (['exposure_time=blahblah'], {'exposure_time': 'blahblah'}),
    ]

@pytest.mark.parametrize("input,expected", getselection_pairs)
def test_getselection(input, expected):
    assert getselection(input) == expected
