dependencies:
  - astropy
  - coverage
  - future
  - pip
  - pytest
  - pylint
  - requests
  - scipy
  - sphinx_rtd_theme
  - sqlalchemy
  - psycopg2
  - pyyaml
  - jinja2
  - cefca::pyfits
  - dateutils
  - pandas
  - boto3
