---
  - hosts: all
    vars_files:
      - secret
    become: true
    tasks:
      - name: Stop Preview service 1
        service: name=fits-service_preview_queue1 state=stopped enabled=yes

      - name: Remove logs
        command: rm -rf /data/logs/service_preview*
      - name: Reset failed Preview Queue Jobs
        postgresql_query:
          login_user: fitsdata
          db: fitsdata
          query: update previewqueue set failed='f'
        become: yes
        become_user: fitsdata

      - name: Start Preview service 1
        service: name=fits-service_preview_queue1 state=started enabled=yes
