"""
This module contains instrument monitoring definitions, eg the keywords that
we capture from each recipe.

By convention, the data checking recipes write output files with the recipe
name as the outpur suffix - ie checkBias1 writes _checkBias1.fits files.
"""

# These tell us the keywords that are recorded by each recipe. Some recipes
# generate multiple output files and we capture different (or no) values from
# some of them.
# recipe_keywords is a dict where the key is the recipe name. If the value is
# a list, we capture those keywords from all files generated by that recipe. If
# the value is a dict, the keys of that dict strings that are substrings of
# filenames from which to extract the keywords in the value list.
recipe_keywords = {
    'checkBiasOSCO': ['OVERSCAN', 'OVERRMS', 'OVERRDNS',
                      'OSCOMEAN', 'OSCOSTDV', 'OSCOMED'],
    'checkBiasBICO': ['BICOMEAN', 'BICOSTDV', 'BICOMED'],
    'checkBiasSTCO': ['STCOMEAN', 'STCOSTDV', 'STCOMED'],
    'checkFlatCounts': ['FLATMEAN', 'FLATSTDV', 'FLATMED'],
    'reduceScience': {'_calibrated': ['ESEEINGR', 'ESEEINGB', 'NCRSFND']},  # GHOST science
}

# These tell us the keywords to include (if they are present) in each report
# type
report_keywords = {
    'checkBias': ['OVERSCAN', 'OVERRMS', 'OVERRDNS',
                  'OSCOMEAN', 'OSCOSTDV', 'OSCOMED',
                  'BICOMEAN', 'BICOSTDV', 'BICOMED',
                  'STCOMEAN', 'STCOSTDV', 'STCOMED'],
    'checkFlat': ['FLATMEAN', 'FLATSTDV', 'FLATMED'],
    'ghostScience': ['ESEEINGR', 'ESEEINGB', 'NCRSFND'],
}

def get_recipe_keywords(recipe, filename):
    recipe_value = recipe_keywords.get(recipe)
    if recipe_value is None:
        return []
    elif isinstance(recipe_value, list):
        return recipe_value
    elif isinstance(recipe_value, dict):
        for filename_substring, value in recipe_value.items():
            if filename_substring in filename:
                return value
        return []
    else:
        return []
