      - name: Setup EPEL
        yum:
          name:
            - epel-release
        when: install_epel
      - name: install packages
        yum:
          name:
            - openssl
            - postgresql
            - postgresql-server
            - postgresql-devel
            - epel-release
            - gcc
            - gcc-c++
            - python3-devel
            - gcc-gfortran
            - cfitsio-devel
            - git
            - python3-pip
            - httpd
            - httpd-devel
            - redhat-rpm-config
            - make
          state: latest
      - name: install SELinux tools
        yum:
          name:
            - policycoreutils-python-utils
        when: selinux_support
