#      - name: target pip version due to bug
#        command: python3 -m pip install --upgrade "pip<10.0"
      - name: target pip version due to bug
        command: python3 -m pip install --upgrade pip
      - name: install psycopg2 binary (so we don't have to compile it) (CentOS 7)
        command: bash -c "python -m pip install psycopg2-binary==2.8.4"
        when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_version < '8'
      - name: install psycopg2 binary (so we don't have to compile it) (CentOS 8)
        command: bash -c "python3 -m pip install psycopg2-binary==2.9.1"
        when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_version >= '8'
#      - name: install python packages for DB
#        command: bash -c "cd /opt/GeminiObsDB && python3 -m pip install -r requirements.txt --upgrade"
      - name: install python packages
        command: bash -c "cd /opt/FitsStorage && python3 -m pip install -r requirements.txt --upgrade"
      - name: install pip for python2 if on CentOS 7
        yum:
          name:
            - python-pip
          state: latest
        when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_version < '8'
      - name: install imexam for DRAGONS (Centos 8)
        command: bash -c "python3 -m pip install imexam specutils"
        when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_version >= '8'
      - name: make dummy specutils folder to satisfy the library's bad logic
        file:
          path: /usr/share/httpd/.specutils
          state: directory
          mode: u+rwx,g+rwx,o+rwx
          owner: fitsdata
          group: fitsdata
        become: true
      - name: install imexam and specutils for DRAGONS (Centos 7)
        command: bash -c "python3 -m pip install imexam specutils"
        when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_version < '8'
