- name: Check for dataflow folder
  stat:
    path: "{{ dataflow_path }}"
  register: dataflow_folder
  when: not is_s3 and not ignore_dataflow
- name: Fail if dataflow folder missing
  fail:
    msg: "Dataflow folder not found"
  when: not dataflow_folder and not is_s3 and not ignore_dataflow
- name: Check for DHS folder
  stat:
    path: /sci/dhs
  register: dhs_folder
  when: is_onsite and is_ops and not ignore_dhs
- name: Fail if DHS folder missing
  fail:
    msg: "DHS folder not found"
  when: "not dhs_folder and ('mko' in inventory_hostname or 'cpofits-lv3' in inventory_hostname)"
- name: Create folders for FitsStorage to work with files
  file:
    path: '{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  with_items:
    - { path: /data/logs, owner: fitsdata, group: fitsdata, mode: "u+rwx,g+rwx,o+rwx" }
    - { path: /data/backups, owner: fitsdata, group: fitsdata, mode: "u+rwx,g-w,o-w" }
    - { path: /data/upload_staging, owner: fitsdata, group: fitsdata, mode: "u+rwx,g+rwx,o+rwx" }
    - { path: /data/z_staging, owner: fitsdata, group: fitsdata, mode: "u+rwx,g+rwx,o+rwx" }
    - { path: /data/s3_staging, owner: fitsdata, group: fitsdata, mode: "u+rwx,g+rwx,o+rwx" }
    - { path: /data/gemini_data, owner: fitsdata, group: fitsdata, mode: "u+rwx,g-w,o-w" }
