      - name: Install ingest queue 1
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_ingest_queue1.service
          dest: /etc/systemd/system/fits-service_ingest_queue1.service
      - name: Install ingest queue 2
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_ingest_queue2.service
          dest: /etc/systemd/system/fits-service_ingest_queue2.service
      - name: Install ingest queue 3
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_ingest_queue.service
          dest: /etc/systemd/system/fits-service_ingest_queue3.service
        when: is_archive and enable_ingest_services
      - name: Setup ingest 3
        lineinfile:
          path: /etc/systemd/system/fits-service_ingest_queue3.service
          line: Description=Fits Service Ingest Queue 3
          regex: Description=
          create: no
        when: is_archive and enable_ingest_services
      - name: Setup ingest 3 exec
        lineinfile:
          path: /etc/systemd/system/fits-service_ingest_queue3.service
          line: ExecStart=/usr/bin/python3 /opt/FitsStorage/fits_storage/scripts/service_ingest_queue.py --demon --lockfile --name=siq3
          regex: ExecStart=
          create: no
        when: is_archive and enable_ingest_services
      - name: Install ingest queue 4
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_ingest_queue.service
          dest: /etc/systemd/system/fits-service_ingest_queue4.service
        when: is_archive and enable_ingest_services
      - name: Setup ingest 4
        lineinfile:
          path: /etc/systemd/system/fits-service_ingest_queue4.service
          line: Description=Fits Service Ingest Queue 4
          regex: Description=
          create: no
        when: is_archive and enable_ingest_services
      - name: Setup ingest 4 exec
        lineinfile:
          path: /etc/systemd/system/fits-service_ingest_queue4.service
          line: ExecStart=/usr/bin/python3 /opt/FitsStorage/fits_storage/scripts/service_ingest_queue.py --demon --lockfile --name=siq4
          regex: ExecStart=
          create: no
        when: is_archive and enable_ingest_services
      - name: Install preview queue 1
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_preview_queue.service
          dest: /etc/systemd/system/fits-service_preview_queue1.service
      - name: Setup preview 1
        lineinfile:
          path: /etc/systemd/system/fits-service_preview_queue1.service
          line: Description=Fits Service Preview Queue 1
          regex: Description=
          create: no
      - name: Setup preview 1 exec
        lineinfile:
          path: /etc/systemd/system/fits-service_preview_queue1.service
          line: ExecStart=/usr/bin/python3 /opt/FitsStorage/fits_storage/scripts/service_preview_queue.py --demon --lockfile --name=spq1
          regex: ExecStart=
          create: no
      - name: Install preview queue 2
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_preview_queue.service
          dest: /etc/systemd/system/fits-service_preview_queue2.service
      - name: Setup preview 2
        lineinfile:
          path: /etc/systemd/system/fits-service_preview_queue2.service
          line: Description=Fits Service Preview Queue 2
          regex: Description=
          create: no
      - name: Setup preview 2 exec
        lineinfile:
          path: /etc/systemd/system/fits-service_preview_queue2.service
          line: ExecStart=/usr/bin/python3 /opt/FitsStorage/fits_storage/scripts/service_preview_queue.py --demon --lockfile --name=spq2
          regex: ExecStart=
          create: no
      - name: Install preview queue 3
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_preview_queue.service
          dest: /etc/systemd/system/fits-service_preview_queue3.service
      - name: Setup preview 3
        lineinfile:
          path: /etc/systemd/system/fits-service_preview_queue3.service
          line: Description=Fits Service Preview Queue 3
          regex: Description=
          create: no
      - name: Setup preview 3 exec
        lineinfile:
          path: /etc/systemd/system/fits-service_preview_queue3.service
          line: ExecStart=/usr/bin/python3 /opt/FitsStorage/fits_storage/scripts/service_preview_queue.py --demon --lockfile --name=spq3
          regex: ExecStart=
          create: no
      - name: Install preview queue 4
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_preview_queue.service
          dest: /etc/systemd/system/fits-service_preview_queue4.service
      - name: Setup preview 4
        lineinfile:
          path: /etc/systemd/system/fits-service_preview_queue4.service
          line: Description=Fits Service Preview Queue 4
          regex: Description=
          create: no
      - name: Setup preview 4 exec
        lineinfile:
          path: /etc/systemd/system/fits-service_preview_queue4.service
          line: ExecStart=/usr/bin/python3 /opt/FitsStorage/fits_storage/scripts/service_preview_queue.py --demon --lockfile --name=spq4
          regex: ExecStart=
          create: no
      - name: Install calcache queue 1
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_calcache_queue.service
          dest: /etc/systemd/system/fits-service_calcache_queue1.service
      - name: Install export queue
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-service_export_queue1.service
          dest: /etc/systemd/system/fits-service_export_queue1.service
      - name: Install API backend
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-api-backend.service
          dest: /etc/systemd/system/fits-api-backend.service
      - name: Install Copy From DHS Service
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-copy_from_dhs.service
          dest: /etc/systemd/system/fits-copy_from_dhs.service
      - name: Install Copy From Visiting Instrument Service
        copy:
          src: ../../otherfiles/etc_systemd_system_{{ visiting_instrument_script }}
          dest: /etc/systemd/system/{{ visiting_instrument_script }}
        when: visiting_instrument_script
      - name: enable services on boot
        ansible.builtin.service:
          name: "{{ item }}"
          enabled: true
          state: started
        when: enable_ingest_services
        with_items: ["fits-service_ingest_queue1", "fits-service_ingest_queue2"]
      - name: Register Ingest service 3
        service: name=fits-service_ingest_queue3 state=started enabled=yes
        when: enable_all_ingest and enable_ingest_services
      - name: Register Ingest service 4
        service: name=fits-service_ingest_queue4 state=started enabled=yes
        when: enable_all_ingest and enable_ingest_services
      - name: Register Preview service 1
        service: name=fits-service_preview_queue1 state=started enabled=yes
        when: enable_preview
      - name: Register Preview service 2
        service: name=fits-service_preview_queue2 state=started enabled=yes
        when: enable_preview
      - name: Register Preview service 3
        service: name=fits-service_preview_queue3 state=started enabled=yes
        when: enable_preview
      - name: Register Preview service 4
        service: name=fits-service_preview_queue4 state=started enabled=yes
        when: enable_preview
      - name: Register Export Queue
        service: name=fits-service_export_queue1 state=started enabled=yes
        when: enable_export
      - name: Register Export Queue (hbf)
        service: name=fits-service_export_queue1 state=stopped enabled=no
        when: not enable_export
      - name: Register CalCache service 1
        service: name=fits-service_calcache_queue1 state=started enabled=yes
        when: is_archive
      - name: Register API service
        service: name=fits-api-backend state=started enabled=yes
      - name: Register DHS service
        service: name=fits-copy_from_dhs state=started enabled=yes
        when: is_ops and is_onsite
      - name: Un-Register DHS service
        service: name=fits-copy_from_dhs state=stopped enabled=no
        when: not is_ops or not is_onsite
      - name: Register Visiting Instrument Service
        service: name={{ visiting_instrument_script }} state=started enabled=yes
        when: {{ visiting_instrument_script }}
      - name: Copy API service script
        copy:
          src: ../../otherfiles/etc_systemd_system_fits-api-backend.service
          dest: /etc/systemd/system/fits-api-backend.service
      - name: Start API service on boot
        service: name=fits-api-backend enabled=yes
