      - name: install postfix
        yum:
          name:
            - postfix
        notify: restart postfix
      - name: configure postfix inet protocols
        lineinfile:
          path: /etc/postfix/main.cf
          line: inet_protocols = ipv4
          regex: inet_protocols
          create: yes
        notify: restart postfix
      - name: configure postfix relay in Hawaii
        lineinfile:
          path: /etc/postfix/main.cf
          line: relayhost = [smtp.hi.gemini.edu]:25
          regex: relayhost
          create: yes
        when: is_hawaii
        notify: restart postfix
      - name: configure postfix relay in Chile
        lineinfile:
          path: /etc/postfix/main.cf
          line: relayhost = [smtp.cl.gemini.edu]:25
          regex: relayhost
          create: yes
        when: is_chile
        notify: restart postfix
      - name: configure postfix in AWS
        copy:
          src: ../../otherfiles/postfix_main.cf
          dest: /etc/postfix/main.cf
        when: is_aws
        notify: restart postfix
      - name: configure postfix transports in AWS
        copy:
          src: ../../otherfiles/postfix_transport
          dest: /etc/postfix/transport
        when: is_aws
        register: updated_postfix_transport
      - name: Create postfix transport.db
        become: true
        become_user: root
        command: cd /etc/postfix && postmap transport
        when: updated_postfix_transport.changed
        notify: restart postfix
      - name: Register postfix service
        service: name=postfix state=started enabled=yes
