      - name: install Repos for Sphinx (dnf-plugins)
#        # shell: "dnf config-manager --enable PowerTools AppStream BaseOS *epel"
#        shell: "dnf config-manager --enable PowerTools AppStream BaseOS"
#        shell: dnf --enablerepo=PowerTools install python3-sphinx
        yum:
          name:
            - dnf-plugins-core
          state: latest
        when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_version >= '8'
#      - name: install Repos for Sphinx
#        shell: yum config-manager --set-enabled PowerTools
#        when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '8'
      - name: install CentOS8/Rocky8 packages
        yum:
          name:
            - libnsl
#            - python3-sphinx
        when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_version >= '8'
      - name: install Sphinx (have to pull direct from the mirror)
        yum:
          name:
            - python3-sphinx-theme-alabaster-0.7.9-7
            - python3-sphinx-1.7.6-2
            - python-sphinx-locale-1.7.6-2
            - python3-mock-2.0.0-11
            - python3-packaging-16.8-9
            - python3-imagesize-1.0.0-2
            - python3-snowballstemmer-1.2.1-6
            - python3-sphinx_rtd_theme-0.3.1-3
            - python3-sphinxcontrib-websupport-1.0.1-10.20180316git
            - fontawesome-fonts-web-4.7.0-4
            - python3-whoosh-2.7.4-9
          state: present
          enablerepo: powertools
        when: build_sphinx
#      - name: install Sphinx (have to pull direct from the mirror)
#        yum:
#          name:
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/aarch64/os/Packages/python3-sphinx-theme-alabaster-0.7.9-7.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/python3-sphinx-1.7.6-2.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/python-sphinx-locale-1.7.6-2.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/python3-mock-2.0.0-11.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/python3-packaging-16.8-9.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/python3-imagesize-1.0.0-2.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/python3-snowballstemmer-1.2.1-6.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/python3-sphinx_rtd_theme-0.3.1-3.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/python3-sphinxcontrib-websupport-1.0.1-10.20180316git.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/fontawesome-fonts-web-4.7.0-4.el8.noarch.rpm
#            - https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/python3-whoosh-2.7.4-9.el8.noarch.rpm
#          state: present
#        when: build_sphinx
# tweak this to deploy when we are about to go live